### PR TITLE
Update ml4xcube v1.0.1

### PR DESCRIPTION
**Pull request by JPeters92**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Julia310** [comment]
@conda-forge-admin, please help.

The packages `xcube`, `sentinelhub`, and `bokeh` are not supposed to be in the `meta.yaml`. The corrected `meta.yaml` with the appropriate changes is contained in [Update ml4xcube v1.0.1 #6](https://github.com/conda-forge/ml4xcube-feedstock/pull/6). I would highly appreciate it if you could prioritize [Update ml4xcube v1.0.1 #6](https://github.com/conda-forge/ml4xcube-feedstock/pull/6) and close the current PR #7.

Thank you for your support!

**Comment by synapticarbors** [comment]
@Julia310 -- are you not able to merge this PR yourself? You should have admin privelages on this feedstock since you are the listed maintainer. Let me know if you don't

**Comment by JPeters92** [comment]
@synapticarbors,
thank you for your prompt response. Currently, I'm unable to merge this pull request. Could you please guide me on how to obtain administrative rights for this feedstock, or consider granting them to me if possible?

**Comment by synapticarbors** [comment]
You should be getting an automated email about being added to the team for this feedstock. I believe you might have to acknowledge via a link in it, but then you'll have admin access.

**Comment by JPeters92** [comment]
@synapticarbors thank you :)

**Pull request merged**
